### PR TITLE
Updated iOS sdk to 10.24.0; Bumped up Android sdks versions

### PR DESCRIPTION
**Pull request by pinguluk**
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation  changes
- [ ] Other... Please describe:

## PR Checklist
Please check your PR fulfills the following requirements:

Bugfixes:
- [ ] Regression testing has been carried out using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to ensure the intended bug is fixed and no regression bugs have been inadvertently introduced.

New features/enhancements:
- [ ] Exhaustive testing has been carried out for the new functionality
- [ ] Regression testing has been carried out to ensure no existing functionality is adversely affected
- [ ] Documentation has been added / updated
- [ ] The [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) has been update to validate/demonstrate the new functionality.

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by ben-kn-app** [comment]
Thank you @pinguluk for your fork, when I compile this fork in xcode 15.3 I get FirebasePlugin.m errors like. 
`No visible @interface for 'GIDSignIn' declares the selector 'signInWithConfiguration:presentingViewController:callback:'`

Probably because of the bump of GoogleSignIn to 7.1.0 

How did you solve these errors?

**Comment by pinguluk** [comment]
> Thank you @pinguluk for your fork, when I compile this fork in xcode 15.3 I get FirebasePlugin.m errors like. `No visible @interface for 'GIDSignIn' declares the selector 'signInWithConfiguration:presentingViewController:callback:'`
> 
> Probably because of the bump of GoogleSignIn to 7.1.0
> 
> How did you solve these errors?

Hey, I got that error too. Perhaps due of the GoogleSignIn bump, but I'll try later to downgrade it and see if it works.

**Comment by pinguluk** [comment]
@ben-kn-app I've downgraded GoogleSignIn back to 6.2.4. Can you pull the latest changes (I think you'll need also to update the Podfile to reflect the changes) and confirm if it's working now?

**Comment by ben-kn-app** [comment]
Thanks! My main concern was complying with the PrivacyInfo.xcprivacy, I've gone back to the original cordova-plugin-firebasex repo and manually created the PrivacyInfo file. App has been accepted this morning by Apple, now I need to update the other 20+ apps in the monorepo. So probably won't get around to testing this today. 

I hope that this will be merged in the original cordova-plufin-firebasex repo, thanks for your dedication and good work!

**Comment by pinguluk** [comment]
> Thanks! My main concern was complying with the PrivacyInfo.xcprivacy, I've gone back to the original cordova-plugin-firebasex repo and manually created the PrivacyInfo file. App has been accepted this morning by Apple, now I need to update the other 20+ apps in the monorepo. So probably won't get around to testing this today.
> 
> I hope that this will be merged in the original cordova-plufin-firebasex repo, thanks for your dedication and good work!

[dpa99c](https://github.com/dpa99c) said he'll try to merge it this week https://github.com/dpa99c/cordova-plugin-firebasex/pull/878#issuecomment-2067269844
Also more info for the PrivacyInfo file https://github.com/dpa99c/cordova-plugin-firebasex/issues/882

**Pull request merged**
